Integration: Add scenario for microshift preset
crc-org/crc pull request #3779
Opened 2023-08-01 08:50 UTC by praveenkumar

With this we can able to test out the microshift preset functionality.
```
$ BUNDLE_LOCATION='--bundle-location=/home/prkumar/.crc/cache/crc_microshift_libvirt_4.13.3_amd64.crcbundle' PULL_SECRET_FILE='--pull-secret-file=/home/prkumar/pull-secret' CRC_BINARY='--crc-binary=/home/prkumar/work/github/crc/out/linux-amd64/' make e2e-story-microshift

  Background:
    Given setting config property "preset" to value "microshift" succeeds                                                                                      # testsuite.go:860 -> github.com/crc-org/crc/test/e2e/testsuite.SetConfigPropertyToValueSucceedsOrFails
[sudo] password for prkumar: 
    And executing single crc setup command succeeds        

[...]
```

2023-08-01 08:58 UTC, gbraad requested changes

2023-08-01 08:58 UTC, gbraad commented on test/e2e/features/story_microshift.feature
> +		And starting CRC with default bundle succeeds
I prefer you would describe the test as:


```
Scenario: Start and expose a basic HTTP service and check after restart
```

2023-08-01 09:01 UTC, jsliacan commented on test/e2e/features/story_microshift.feature
> +	@microshift @testdata @linux @windows @mac
Not sure `@mac` equals to `$GOOS`. I think `@darwin` is what works.

2023-08-01 10:56 UTC, gbraad commented on test/e2e/testsuite/testsuite.go
> +	pflag.StringVar(&bundleLocation, "bundle-location", "", "Path to the bundle to be used in tests")
👍

2023-08-01 10:56 UTC, gbraad commented on test/e2e/testsuite/testsuite.go
> +	pflag.StringVar(&CRCExecutable, "crc-binary", "", "Path to the CRC executable to be tested")
👍

2023-08-01 10:57 UTC, gbraad approved these changes

2023-08-01 11:21 UTC, praveenkumar commented
/hold

Need to verify the actual microshift test runs or not.

2023-08-01 12:44 UTC, praveenkumar commented
/test e2e-microshift-crc

2023-08-02 05:37 UTC, gbraad approved these changes

2023-08-02 10:24 UTC, praveenkumar commented
/unhold

2023-08-02 10:24 UTC, merged

2023-08-16 14:35 UTC, cfergeau commented
Unclear to me why this seems to be a wholly different test from the other ones we have? Could we share the same "httpd" test for both microshift and openshift?

2023-08-21 05:47 UTC, praveenkumar commented
> Unclear to me why this seems to be a wholly different test from the other ones we have? Could we share the same "httpd" test for both microshift and openshift?

@cfergeau `httpd` scenario is part of `story_openshift` feature where it expect the cluster of openshift running (as part of background). if a scenario can be abstracted which can consumed for different features then we didn't have to duplicate this test and consumed for both the scenarios but I didn't find a way.

2023-08-21 08:36 UTC, adrianriobo commented
I would suggest add a config flag to inform on which preset we want to run the tests (Default value to `openshift`).  

That flag can be used within the background steps (making them dynamic based on the flag). With that approach you can avoid the duplication.

2023-08-21 12:34 UTC, cfergeau commented
Took another look at this, and for some reason I had missed https://github.com/crc-org/crc/blob/97705a008eda801ba291fe3b9982af464d4759e0/test/e2e/features/story_openshift.feature#L13-L37 and thought story_microshift.feature was totally different from the http OpenShift tests.
This is not the case, it's the same code, even though it's duplicated.

Imo it's really useful to add a comment before duplicated code to remind people when touching one of the code blocks, the other one needs to be updated. And documentingin the commit log why this was duplicated is also useful if one wants to try to improve things.