docs: clarify Windows OS requirements
crc-org/crc pull request #3918
Opened 2023-11-16 09:56 UTC by themr0c

docs: clarify Windows OS requirements

2023-11-16 11:27 UTC, gbraad requested changes, later dismissed

2023-11-16 11:27 UTC, gbraad commented on docs/modules/getting_started/partials/ref_minimum-system-requirements.adoc
> +* {prod} does not work on {msw} 10 Home Edition.
Home Edition . no need to mention version

2023-11-20 11:01 UTC, themr0c commented on docs/modules/getting_started/partials/ref_minimum-system-requirements.adoc
> +* {prod} does not work on {msw} 10 Home Edition.
```suggestion
* {prod} does not work on {msw} Home Edition.
```

2023-11-23 11:35 UTC, gbraad approved these changes

2023-11-24 08:53 UTC, themr0c commented
/retest

2023-11-24 16:42 UTC, merged