telemetry: add no-op functionality to SegmentClient to make sure errors in initialization are not fatal
crc-org/crc pull request #4100
Opened 2024-04-03 09:45 UTC by redbeam

**Fixes:** Issue #4085

A new field has been added to Client struct signalling whether the client has been initialized properly. Default value is `false` and it is set to `true` only if the initialization went as expected.
Methods on Client check if this field is true before progressing further.

In case of any error during initialization, an empty Client is returned (and its methods do nothing).

2024-04-03 15:01 UTC, cfergeau reviewed
Looks good to me, just not sure about the `isInitProperly` name.

2024-04-03 15:01 UTC, cfergeau commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
`isInitProperly`  is a bit 'ungrammatical', but so is `isInitedProperly` :-/
For what it's worth, I think I would store the error we got at init time instead of just a boolean, so this could be `initError` (and actually, even as a boolean it would be fine).

Or it might be possible to deal with this without a boolean at all, just:
```
var NoopClient = &Client{}
```
then in error cases, you return `return NoopClient, err`
and the `if !c.isInitProperly {` checks become `if c == NoopClient`

These are just various suggestions, I'm fine with your approach with a boolean, though I'd prefer if we slightly improved the naming.

2024-04-04 15:21 UTC, redbeam commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
I like the approach with storing the error.
Thanks for the review!

2024-04-10 09:55 UTC, gbraad commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
`hasFinishedInit` would be more grammatically correct, however storing this as a state is not relevant. The rest of the execution should not care about the error state. I prefer the `c == NoopClient` checks (more in line with proper OOP practices) => more clearly indicating the state/situation without comments and allows reuse for situations where we might want to force a `NoopClient`, like CI (testing the output, but not recording). So, why is there not a `NoopClient` mock-implementation?

2024-04-10 09:57 UTC, gbraad requested changes
Would like to understand what it takes not to keep state. The `NoopClient` should work without specific knowledge to what happened... and if needed, a typecheck would be preferred.

2024-04-16 22:53 UTC, redbeam commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
I agree with your remarks Gerard. I changed the implementation to use NoopClient.

2024-04-17 10:23 UTC, gbraad commented
I think something went wrong during rebase, as I see some stuff about snyk and the `sw_vers` fix. Do not believe they are pat of this PR. 

However, the rest looks good to me,

2024-04-18 00:57 UTC, redbeam commented
/retest

2024-04-18 06:38 UTC, gbraad commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
There are now commits related to a fix from Praveen. I do not believe they are part of this PR and might be due to a rebase?

2024-04-19 17:41 UTC, redbeam commented on pkg/crc/segment/segment.go
> +	isInitProperly bool
Yes, that was a mistake on my part. I reverted the branch and pushed only the following commit. Now there should only be my two commits.

2024-04-22 10:36 UTC, cfergeau reviewed
Looks good to me, I'd squash the 2 commits though, we don't need to have the `isInitProperly` version of the code in the upstream git history.
 The shortlog for both commits overflows on github, it's supposed to be kept short, with a longer description in the longer commit log. 
 ```
telemetry: add no-op functionality

Currently, when telemetry initialization fails, this is a hard failure for the `crc` command and daemon, and they exit.
This commit handles this more gracefully, when there's a telemetry initialization failure, an empty `NoOp` `Client` instance is returned, and all `Client` methods check for this `NoOp` instance and return early if needed.
```

2024-04-23 07:03 UTC, gbraad commented
> The shortlog for both commits overflows on github, it's supposed to be kept short, 

About 20 to 30 characters.

2024-04-28 21:15 UTC, redbeam commented
@gbraad @cfergeau Thanks for the suggestions. Everything should be fixed now.

2024-04-30 05:03 UTC, merged